# Generated by Django 6.0 on 2026-04-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owncompany',
            name='bank_address',
            field=models.TextField(blank=True, verbose_name='Адрес банка'),
        ),
        migrations.AddField(
            model_name='owncompany',
            name='bank_bik',
            field=models.CharField(blank=True, max_length=32, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='owncompany',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='owncompany',
            name='correspondent_account',
            field=models.CharField(blank=True, max_length=64, verbose_name='Корреспондентский счет'),
        ),
        migrations.AddField(
            model_name='owncompany',
            name='director_basis',
            field=models.CharField(blank=True, max_length=255, verbose_name='Основание полномочий'),
        ),
        migrations.AddField(
            model_name='owncompany',
            name='director_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Руководитель'),
        ),
        migrations.AddField(
            model_name='owncompany',
            name='edo_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID в ЭДО'),
        ),
        migrations.AddField(
            model_name='owncompany',
            name='edo_operator',
            field=models.CharField(blank=True, max_length=255, verbose_name='Оператор ЭДО'),
        ),
        migrations.AddField(
            model_name='owncompany',
            name='postal_address',
            field=models.TextField(blank=True, verbose_name='Почтовый адрес'),
        ),
        migrations.AddField(
            model_name='owncompany',
            name='settlement_account',
            field=models.CharField(blank=True, max_length=64, verbose_name='Расчетный счет'),
        ),
    ]
