# Generated by Django 6.0 on 2026-04-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head_manager', '0002_owncompany_bank_address_owncompany_bank_bik_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='bank_address',
            field=models.TextField(blank=True, verbose_name='Адрес банка'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='bank_bik',
            field=models.CharField(blank=True, max_length=32, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='correspondent_account',
            field=models.CharField(blank=True, max_length=64, verbose_name='Корреспондентский счет'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='postal_address',
            field=models.TextField(blank=True, verbose_name='Почтовый адрес'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='settlement_account',
            field=models.CharField(blank=True, max_length=64, verbose_name='Расчетный счет'),
        ),
    ]
