# Generated by Django 5.1 on 2026-01-14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sku", "0008_agency_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_type", models.CharField(default="processing", max_length=32)),
                ("order_id", models.CharField(max_length=64)),
                ("sku", models.CharField(max_length=64)),
                ("size", models.CharField(blank=True, max_length=64)),
                ("barcode", models.CharField(blank=True, max_length=64)),
                ("goods_type", models.CharField(blank=True, max_length=64)),
                ("qty", models.PositiveIntegerField(default=0)),
                (
                    "state",
                    models.CharField(
                        choices=[("processing", "В обработке")],
                        default="processing",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_states",
                        to="sku.agency",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["agency", "state"], name="sklad_inven_agency__2d3e3a_idx"),
                    models.Index(fields=["agency", "sku"], name="sklad_inven_agency__4b1b2d_idx"),
                    models.Index(fields=["order_type", "order_id"], name="sklad_inven_order_t_1a2b3c_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=[
                            "agency",
                            "order_type",
                            "order_id",
                            "sku",
                            "size",
                            "barcode",
                            "goods_type",
                            "state",
                        ],
                        name="uniq_inventory_state_row",
                    )
                ],
            },
        ),
    ]
