# Generated by Django 6.0 on 2026-02-20 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0001_inventory_state'),
        ('sku', '0008_agency_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPalletState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(default='receiving', max_length=32)),
                ('order_id', models.CharField(max_length=64)),
                ('sku', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('size', models.CharField(blank=True, max_length=64)),
                ('barcode', models.CharField(blank=True, max_length=64)),
                ('goods_type', models.CharField(blank=True, max_length=64)),
                ('qty', models.PositiveIntegerField(default=0)),
                ('box_code', models.CharField(blank=True, max_length=128)),
                ('pallet_code', models.CharField(blank=True, max_length=128)),
                ('zone', models.CharField(blank=True, max_length=16)),
                ('row', models.PositiveIntegerField(default=0)),
                ('section', models.PositiveIntegerField(default=0)),
                ('tier', models.PositiveIntegerField(default=0)),
                ('cell', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(choices=[('warehouse', 'На складе')], default='warehouse', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='inventorystate',
            new_name='sklad_inven_agency__666805_idx',
            old_name='sklad_inven_agency__2d3e3a_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorystate',
            new_name='sklad_inven_agency__cbadfe_idx',
            old_name='sklad_inven_agency__4b1b2d_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorystate',
            new_name='sklad_inven_order_t_11f28a_idx',
            old_name='sklad_inven_order_t_1a2b3c_idx',
        ),
        migrations.AlterField(
            model_name='inventorystate',
            name='state',
            field=models.CharField(choices=[('processing', 'В обработке'), ('warehouse', 'На складе')], default='processing', max_length=32),
        ),
        migrations.AddField(
            model_name='stockpalletstate',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_pallet_states', to='sku.agency'),
        ),
        migrations.AddIndex(
            model_name='stockpalletstate',
            index=models.Index(fields=['agency', 'state'], name='sklad_stock_agency__f95542_idx'),
        ),
        migrations.AddIndex(
            model_name='stockpalletstate',
            index=models.Index(fields=['agency', 'sku'], name='sklad_stock_agency__b5b9fc_idx'),
        ),
        migrations.AddIndex(
            model_name='stockpalletstate',
            index=models.Index(fields=['agency', 'pallet_code'], name='sklad_stock_agency__d0eade_idx'),
        ),
        migrations.AddIndex(
            model_name='stockpalletstate',
            index=models.Index(fields=['order_type', 'order_id'], name='sklad_stock_order_t_e6d1ad_idx'),
        ),
    ]
