# Generated by Django 6.0 on 2026-02-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0002_stockpalletstate_and_more'),
        ('sku', '0008_agency_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stockpalletstate',
            constraint=models.CheckConstraint(condition=models.Q(('pallet_code', ''), models.Q(models.Q(('pallet_code', ''), _negated=True), models.Q(('zone', ''), _negated=True), models.Q(('location', ''), _negated=True)), _connector='OR'), name='stock_pallet_location_required'),
        ),
    ]
