# Generated by Django 6.0 on 2026-03-19 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0003_stockpalletstate_stock_pallet_location_required'),
        ('sku', '0008_agency_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpalletstate',
            name='sku_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_pallet_states', to='sku.sku', verbose_name='SKU'),
        ),
    ]
