# Generated by Codex on 2026-01-25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sku", "0008_agency_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketSyncReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marketplace", models.CharField(choices=[("WB", "Wildberries"), ("OZON", "Ozon")], max_length=16)),
                ("status", models.CharField(choices=[("ok", "ok"), ("error", "error")], max_length=16)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField()),
                ("duration_sec", models.FloatField(default=0)),
                ("processed", models.PositiveIntegerField(default=0)),
                ("created", models.PositiveIntegerField(default=0)),
                ("updated", models.PositiveIntegerField(default=0)),
                ("barcodes_created", models.PositiveIntegerField(default=0)),
                ("errors", models.JSONField(blank=True, default=list)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_sync_reports",
                        to="sku.agency",
                    ),
                ),
            ],
            options={
                "ordering": ["-finished_at"],
            },
        ),
    ]
