# Generated by Django 6.0 on 2026-01-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingPrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('printing', 'Printing'), ('printed', 'Printed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('order_id', models.CharField(blank=True, max_length=64)),
                ('card_id', models.CharField(blank=True, max_length=128)),
                ('article', models.CharField(blank=True, max_length=128)),
                ('barcode', models.CharField(max_length=128)),
                ('size', models.CharField(blank=True, max_length=64)),
                ('printer_name', models.CharField(blank=True, max_length=255)),
                ('label_png_base64', models.TextField(blank=True)),
                ('label_width_mm', models.PositiveIntegerField(default=58)),
                ('label_height_mm', models.PositiveIntegerField(default=40)),
                ('requested_by', models.CharField(blank=True, max_length=150)),
                ('agent', models.CharField(blank=True, max_length=128)),
                ('error', models.TextField(blank=True)),
            ],
        ),
    ]
