# Generated by Django 6.0 on 2026-04-08 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing_app', '0002_processingflowsession'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='processingflowsession',
            new_name='processing__order_i_b04c0e_idx',
            old_name='processing__order_i_09d833_idx',
        ),
        migrations.RenameIndex(
            model_name='processingflowsession',
            new_name='processing__agent_i_2a5442_idx',
            old_name='processing__agent_i_1e3f7f_idx',
        ),
        migrations.RenameIndex(
            model_name='processingflowsession',
            new_name='processing__user_id_83ac89_idx',
            old_name='processing__user_id_6f2105_idx',
        ),
    ]
