# Generated by Django 6.0 on 2026-03-19 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sku', '0008_agency_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Номер заявки')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Новая'), ('reserved', 'Зарезервирована'), ('picking', 'В отборе'), ('packed', 'Упакована'), ('shipped', 'Отгружена'), ('partial_shipped', 'Отгружена частично'), ('canceled', 'Отменена')], default='draft', max_length=32, verbose_name='Статус')),
                ('delivery_type', models.CharField(choices=[('marketplace', 'Маркетплейс'), ('courier', 'Курьер'), ('pickup', 'Самовывоз'), ('other', 'Другое')], default='marketplace', max_length=32, verbose_name='Тип отгрузки')),
                ('destination_address', models.TextField(blank=True, verbose_name='Адрес отгрузки')),
                ('planned_ship_date', models.DateField(blank=True, null=True, verbose_name='Плановая дата отгрузки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('reserved_at', models.DateTimeField(blank=True, null=True, verbose_name='Резерв подтвержден')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Отгружена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipping_orders', to='sku.agency', verbose_name='Клиент')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_orders', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Заявка на отгрузку',
                'verbose_name_plural': 'Заявки на отгрузку',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(max_length=64, verbose_name='Артикул')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('size', models.CharField(blank=True, max_length=64, verbose_name='Размер')),
                ('barcode', models.CharField(blank=True, max_length=64, verbose_name='Штрихкод')),
                ('goods_type', models.CharField(blank=True, max_length=64, verbose_name='Тип товара')),
                ('qty_requested', models.PositiveIntegerField(default=0, verbose_name='Запрошено')),
                ('qty_reserved', models.PositiveIntegerField(default=0, verbose_name='Зарезервировано')),
                ('qty_shipped', models.PositiveIntegerField(default=0, verbose_name='Отгружено')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipping.shippingorder', verbose_name='Заявка')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_items', to='sku.sku', verbose_name='SKU')),
            ],
            options={
                'verbose_name': 'Позиция отгрузки',
                'verbose_name_plural': 'Позиции отгрузки',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ShippingReserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(max_length=64, verbose_name='Артикул')),
                ('size', models.CharField(blank=True, max_length=64, verbose_name='Размер')),
                ('barcode', models.CharField(blank=True, max_length=64, verbose_name='Штрихкод')),
                ('goods_type', models.CharField(blank=True, max_length=64, verbose_name='Тип товара')),
                ('qty', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_reserves', to='sku.agency', verbose_name='Клиент')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_reserves', to=settings.AUTH_USER_MODEL, verbose_name='Зарезервировал')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='shipping.shippingorderitem', verbose_name='Позиция')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='shipping.shippingorder', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Резерв отгрузки',
                'verbose_name_plural': 'Резервы отгрузки',
            },
        ),
        migrations.AddIndex(
            model_name='shippingorder',
            index=models.Index(fields=['status', 'created_at'], name='shipping_sh_status_461a02_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingorder',
            index=models.Index(fields=['agency', 'status'], name='shipping_sh_agency__48d10d_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingorderitem',
            index=models.Index(fields=['order', 'sku_code', 'size'], name='shipping_sh_order_i_00a896_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingorderitem',
            index=models.Index(fields=['sku_code', 'barcode'], name='shipping_sh_sku_cod_3afe41_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingreserve',
            index=models.Index(fields=['agency', 'sku_code', 'size'], name='shipping_sh_agency__d21046_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingreserve',
            index=models.Index(fields=['order', 'item'], name='shipping_sh_order_i_021605_idx'),
        ),
    ]
