# Generated by Django 6.0 on 2026-03-19 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
        ('sku', '0008_agency_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingorder',
            name='marketplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_orders', to='sku.market', verbose_name='Маркетплейс'),
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='slot_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата слота'),
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('fulfillment', 'Авто фулфилмента'), ('client', 'Авто клиента')], default='', max_length=32, verbose_name='Тип авто'),
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='wb_supply_barcode',
            field=models.CharField(blank=True, max_length=128, verbose_name='ШК поставки WB'),
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='wb_transit_warehouse',
            field=models.BooleanField(default=False, verbose_name='Транзитный склад WB'),
        ),
    ]
