# Generated by Django 6.0 on 2026-03-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_shippingorder_marketplace_shippingorder_slot_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingorder',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Телефон водителя'),
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='eta_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Плановая дата/время прибытия'),
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='expected_boxes',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество мест (план)'),
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='place_type',
            field=models.CharField(blank=True, choices=[('pallet', 'Паллет'), ('box', 'Короб'), ('bag', 'Мешок')], default='', max_length=16, verbose_name='Тип мест'),
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=32, verbose_name='Номер авто'),
        ),
    ]
