# Generated by Django 6.0 on 2026-03-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_shippingorder_driver_phone_shippingorder_eta_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingorder',
            name='destination_warehouse',
            field=models.CharField(blank=True, max_length=255, verbose_name='Склад назначения'),
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='shipping_barcode',
            field=models.CharField(blank=True, max_length=128, verbose_name='ШК отгрузки'),
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='supply_type',
            field=models.CharField(blank=True, choices=[('box', 'Короб'), ('monopallet', 'Монопаллет'), ('supersafe', 'Супер сейф')], default='', max_length=32, verbose_name='Тип поставки'),
        ),
        migrations.AlterField(
            model_name='shippingorder',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('fulfillment', 'Транспорт ФуллБокс'), ('client', 'Транспорт Клиента')], default='', max_length=32, verbose_name='Тип авто'),
        ),
    ]
