# Generated by Django 6.0 on 2026-03-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_shippingorder_destination_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingorder',
            name='transit_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Транзитный адрес'),
        ),
    ]
