# Generated by Django 6.0 on 2026-04-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0006_shippingorderattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingorder",
            name="slot_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Время слота"),
        ),
        migrations.AlterField(
            model_name="shippingorder",
            name="shipping_barcode",
            field=models.CharField(blank=True, max_length=128, verbose_name="ШК поставки"),
        ),
    ]
