# Generated by Django 6.0 on 2026-04-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0007_shippingorder_slot_time_and_shipping_barcode_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Новая'), ('reserved', 'Зарезервирована'), ('storekeeper_accepted', 'Принята в работу складом'), ('picking', 'В отборе'), ('packed', 'Упакована'), ('shipped', 'Отгружена'), ('partial_shipped', 'Отгружена частично'), ('canceled', 'Отменена')], default='draft', max_length=32, verbose_name='Статус'),
        ),
    ]
