# Generated by Django 6.0 on 2026-01-23 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sku', '0008_agency_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkingCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('processing', 'Обработка'), ('receiving', 'Приемка'), ('placement', 'Размещение'), ('shipping', 'Отгрузка'), ('other', 'Прочее')], default='processing', max_length=32)),
                ('order_id', models.CharField(blank=True, max_length=64)),
                ('sku_code', models.CharField(max_length=64, verbose_name='Артикул')),
                ('size', models.CharField(blank=True, max_length=64, verbose_name='Размер')),
                ('barcode', models.CharField(blank=True, max_length=128, verbose_name='Штрихкод')),
                ('code', models.TextField(unique=True, verbose_name='Код ЧЗ')),
                ('source', models.CharField(choices=[('scan', 'Сканер'), ('import', 'Импорт')], default='scan', max_length=16, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marking_codes', to='sku.agency', verbose_name='Клиент')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marking_codes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marking_codes', to='sku.sku', verbose_name='SKU')),
            ],
            options={
                'verbose_name': 'Код ЧЗ',
                'verbose_name_plural': 'Коды ЧЗ',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_type', 'order_id'], name='marking_mar_order_t_f79ff9_idx'), models.Index(fields=['sku_code', 'size'], name='marking_mar_sku_cod_4e4d6b_idx')],
            },
        ),
    ]
