# Generated by Django 6.0 on 2025-12-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_task_assignments"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="observers",
            field=models.ManyToManyField(
                blank=True,
                related_name="observed_tasks",
                to="employees.employee",
                verbose_name="Наблюдатели",
            ),
        ),
    ]
