# Generated by Django 6.0 on 2025-12-22 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_alter_employee_role"),
        ("todo", "0003_task_observers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="observers",
        ),
        migrations.AddField(
            model_name="task",
            name="observer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="observed_tasks",
                to="employees.employee",
                verbose_name="Наблюдатель",
            ),
        ),
    ]
