# Generated by Django 6.0 on 2025-12-22 01:10

from datetime import timedelta

from django.db import migrations, models
from django.utils import timezone

import todo.models


def set_missing_due_dates(apps, schema_editor):
    Task = apps.get_model("todo", "Task")
    tomorrow = timezone.now() + timedelta(days=1)
    Task.objects.filter(due_date__isnull=True).update(due_date=tomorrow)


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0005_task_comments_attachments"),
    ]

    operations = [
        migrations.RunPython(set_missing_due_dates, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(default=todo.models.default_due_date, verbose_name="Дедлайн"),
        ),
    ]
