# Generated by Django 6.0 on 2025-12-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_task_due_date_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('backlog', 'Просрочены'), ('in_progress', 'Сегодня'), ('done', 'Готово'), ('blocked', 'Скоро')], default='backlog', max_length=32, verbose_name='Статус'),
        ),
    ]
