# Generated by Django 6.0 on 2025-12-18 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(max_length=64, unique=True, verbose_name='Артикул')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('color', models.CharField(blank=True, max_length=64, null=True, verbose_name='Цвет')),
                ('size', models.CharField(blank=True, max_length=64, null=True, verbose_name='Размер')),
                ('composition', models.CharField(blank=True, max_length=255, null=True, verbose_name='Состав')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Вес, кг')),
                ('length_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Длина, мм')),
                ('width_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Ширина, мм')),
                ('height_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Высота, мм')),
                ('honest_sign', models.BooleanField(default=False, verbose_name='Честный знак')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('source', models.CharField(choices=[('manual', 'Создан вручную'), ('marketplace', 'Синхронизация маркетплейс')], default='manual', max_length=32, verbose_name='Источник')),
                ('source_reference', models.CharField(blank=True, max_length=128, null=True, verbose_name='Внешний идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SKU',
                'verbose_name_plural': 'Номенклатура',
                'ordering': ['sku_code'],
            },
        ),
        migrations.CreateModel(
            name='SKUBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=64, unique=True, verbose_name='Штрихкод')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='sku.sku', verbose_name='SKU')),
            ],
            options={
                'verbose_name': 'Штрихкод',
                'verbose_name_plural': 'Штрихкоды',
                'ordering': ['-is_primary', 'value'],
            },
        ),
        migrations.CreateModel(
            name='SKUPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Ссылка на фото')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='sku.sku', verbose_name='SKU')),
            ],
            options={
                'verbose_name': 'Фото товара',
                'verbose_name_plural': 'Фото товара',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(max_length=64, verbose_name='Маркетплейс')),
                ('external_id', models.CharField(max_length=128, verbose_name='Внешний ID')),
                ('sync_mode', models.CharField(choices=[('readonly', 'Только чтение'), ('overwrite', 'Перезаписывать при синхронизации')], default='readonly', max_length=32, verbose_name='Режим синхронизации')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_bindings', to='sku.sku', verbose_name='SKU')),
            ],
            options={
                'verbose_name': 'Привязка к маркетплейсу',
                'verbose_name_plural': 'Привязки к маркетплейсам',
                'unique_together': {('marketplace', 'external_id')},
            },
        ),
    ]
