# Generated by Django 6.0 on 2025-12-18 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('agn_name', models.CharField(max_length=255, verbose_name='Организация')),
                ('inn', models.CharField(blank=True, max_length=32, null=True, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=32, null=True, verbose_name='КПП')),
                ('adres', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='USER_ID')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='Телефон')),
                ('sign_oferta', models.BooleanField(default=False, verbose_name='Подписана оферта')),
                ('pref', models.CharField(blank=True, max_length=32, null=True, verbose_name='Префикс')),
                ('fio_agn', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО контактного')),
                ('use_nds', models.BooleanField(default=False, verbose_name='Использует НДС')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('mened_user_id', models.IntegerField(blank=True, null=True, verbose_name='MENED_USER_ID')),
                ('fakt_adres', models.TextField(blank=True, null=True, verbose_name='Фактический адрес')),
                ('ogrn', models.CharField(blank=True, max_length=32, null=True, verbose_name='ОГРН')),
                ('bank_bik', models.CharField(blank=True, max_length=32, null=True, verbose_name='БИК')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Банк')),
                ('bank_itog_account', models.CharField(blank=True, max_length=64, null=True, verbose_name='Р/счет')),
                ('bank_koresp_account', models.CharField(blank=True, max_length=64, null=True, verbose_name='Корр. счет')),
                ('contract_numb', models.CharField(blank=True, max_length=64, null=True, verbose_name='Номер договора')),
                ('contract_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на договор')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['agn_name'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='Маркетплейс')),
            ],
            options={
                'verbose_name': 'Маркетплейс',
                'verbose_name_plural': 'Маркетплейсы',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='sku',
            name='additional_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Доп. наименование'),
        ),
        migrations.AddField(
            model_name='sku',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='sku',
            name='code',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='sku',
            name='cr_product_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата производства'),
        ),
        migrations.AddField(
            model_name='sku',
            name='end_product_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок годности'),
        ),
        migrations.AddField(
            model_name='sku',
            name='gender',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='sku',
            name='img',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на фото'),
        ),
        migrations.AddField(
            model_name='sku',
            name='img_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к фото'),
        ),
        migrations.AddField(
            model_name='sku',
            name='made_in',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Страна производства'),
        ),
        migrations.AddField(
            model_name='sku',
            name='name_print',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название для печати'),
        ),
        migrations.AddField(
            model_name='sku',
            name='season',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Сезон'),
        ),
        migrations.AddField(
            model_name='sku',
            name='sign_akciz',
            field=models.BooleanField(default=False, verbose_name='Признак акциза'),
        ),
        migrations.AddField(
            model_name='sku',
            name='tovar_category',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Категория товара'),
        ),
        migrations.AddField(
            model_name='sku',
            name='type_tovar',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Тип товара'),
        ),
        migrations.AddField(
            model_name='sku',
            name='use_nds',
            field=models.BooleanField(default=False, verbose_name='Использует НДС'),
        ),
        migrations.AddField(
            model_name='sku',
            name='vid_tovar',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Вид товара'),
        ),
        migrations.AddField(
            model_name='sku',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Объем'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='color',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Цвет (текст)'),
        ),
        migrations.AddField(
            model_name='sku',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sku.agency', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='sku',
            name='color_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sku.color', verbose_name='Цвет из справочника'),
        ),
        migrations.AddField(
            model_name='sku',
            name='market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sku.market', verbose_name='Маркетплейс'),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('stor_name', models.CharField(max_length=128, verbose_name='Склад')),
                ('agn_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Организация (по имени)')),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='sku.agency', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='sku',
            name='stor_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sku.store', verbose_name='Склад хранения'),
        ),
        migrations.CreateModel(
            name='MarketCredential',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('market_key', models.TextField(blank=True, null=True, verbose_name='Ключ доступа')),
                ('client_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='Client ID')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_credentials', to='sku.agency', verbose_name='Клиент')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='sku.market', verbose_name='Маркетплейс')),
            ],
            options={
                'verbose_name': 'Ключ маркетплейса',
                'verbose_name_plural': 'Ключи маркетплейсов',
                'unique_together': {('agency', 'market')},
            },
        ),
    ]
