# Generated by Django 6.0 on 2025-12-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0002_agency_color_market_sku_additional_name_sku_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='agn_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Организация'),
        ),
    ]
