# Generated by Django 6.0 on 2025-12-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0003_alter_agency_agn_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
    ]
