# Generated by Django 6.0 on 2025-12-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0004_sku_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='sku_code',
            field=models.CharField(max_length=64, verbose_name='Артикул'),
        ),
        migrations.AddConstraint(
            model_name='sku',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('agency', 'sku_code'), name='uniq_sku_code_per_agency_active'),
        ),
    ]
