# Generated by Django 6.0 on 2025-12-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0005_alter_sku_sku_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Архивирован'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
