# Generated by Django 6.0 on 2026-04-28 17:50

from django.db import migrations, models


def copy_legacy_weight_to_gross(apps, schema_editor):
    SKU = apps.get_model('sku', 'SKU')
    SKU.objects.filter(weight_kg__isnull=False, weight_gross_kg__isnull=True).update(
        weight_gross_kg=models.F('weight_kg')
    )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0009_agency_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='weight_gross_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Вес брутто, кг'),
        ),
        migrations.AddField(
            model_name='sku',
            name='weight_net_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Вес нетто, кг'),
        ),
        migrations.RunPython(copy_legacy_weight_to_gross, noop_reverse),
    ]
