# Generated by Django 6.0 on 2025-12-19 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sku', '0003_alter_agency_agn_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление'), ('clone', 'Клонирование')], max_length=32, verbose_name='Действие')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('snapshot', models.JSONField(blank=True, null=True, verbose_name='Снимок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='sku.sku')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Журнал изменений SKU',
                'verbose_name_plural': 'Журналы изменений SKU',
                'ordering': ['-created_at'],
            },
        ),
    ]
