# Generated by Django 6.0 on 2025-12-21 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sku', '0006_agency_archived_alter_agency_id'),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=128, verbose_name='ID заявки')),
                ('order_type', models.CharField(default='receiving', max_length=64, verbose_name='Тип заявки')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('status', 'Статус'), ('comment', 'Комментарий'), ('upload', 'Файлы')], max_length=32, verbose_name='Действие')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('payload', models.JSONField(blank=True, null=True, verbose_name='Данные')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда')),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sku.agency', verbose_name='Клиент')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Аудит заявки',
                'verbose_name_plural': 'Аудит заявок',
                'ordering': ['-created_at'],
            },
        ),
    ]
