# Generated by Django 6.0 on 2025-12-21 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditentry_journal_auditjournal'),
        ('audit', '0002_orderauditentry'),
    ]

    operations = [
    ]
