# Generated by Django 6.0 on 2025-12-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('director', 'Директор'), ('accountant', 'Бухгалтер'), ('head_manager', 'Главный менеджер'), ('manager', 'Менеджер'), ('storekeeper', 'Кладовщик'), ('picker', 'Сборщик'), ('developer', 'Разработчик')], max_length=32, verbose_name='Роль'),
        ),
    ]
